name: External API Trigger

on:
  repository_dispatch:
    types: [external-trigger]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Echo Hello
      run: echo "hello"
