name: Azure ML Trigger

on:
  repository_dispatch:
    types: [Model-registered]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Do something
      run: echo "Model has been registered!"
